### ISSUE TITLE
[product API] post method 관련 몇가지 의문사항

### ISSUE THREAD

**Issue by DevelopDestroyer** [DevelopDestroyer/UglyAgriFood#11]
해당 부분은 아직 구현은 안하고 Swagger만 살펴보았는데 몇가지 궁금한 점이 있습니다.

1. oneDayAvgPrice과 같은 멤버변수들은 아마 API에서 찾아오는 것으로 보여지는데 클라이언트의 JSON형식에 존재해야하나요? 아니면 null이나 공백이라도 넣어보내주어야 하는건지 궁금해요

2. imageUrl의 경우에도 추후 백단에서 상품정보를 GET할때만 보여지는 것 같고 클라이언트에서 보내줄 내용은 없어 보입니다.

3. category는 사전 이야기한대로 그냥 '농산', '수산' 등과 같은 문자열을 보내면 돼는 것 맞죠..? (swagger request example 상에는 'AGRICULTURAL_PRODUCTS' 이런거를 보내주고있음)

4. kind는 어떤 정보를 담아보내야하는 멤버변수인가요 (category와 의미가 유사해보여서 헷갈리기도합니다..)

5. 화면설계상에 클라이언트에게 입력받아야 할 것같은 요소들을 입력받고 있지 않은 것 같습니다. (ex. 원산지, 생산자, 보관방법, 제조년월일 등등등...)

6. 마지막으루.. 썸네일이미지와 상품설명이미지에 대한 업로드는 별도 API로 제공할 예정인가요??

@chudaeyoun

**Comment by chudaeyoun** [comment]
1. api 로 보낼때 들어가있는것은 빼야함. 저거는 클라에서 변동되는 데이터가 아니라 안들고 있어도 될듯

2. 아직 미구현

3. 그렇게 얘기 됐으면 문자열로 보내면됨. api dto 를 문자열로 바꿔야할듯

4. 이건 크롤링한 데이터로 고정된 값으로 알고 있는데, 
RetailProduct 안에 들은건 api 로 안쏴도 될듯.(재홍이한테 물어봐야함)

5. 아직 필요한 정보를 입력받아서 하는거 미구현

6. 아직 미구현인데 생각 필요


아직 api 는 db 도메인 가지고 일단 틀만 만들어나서 
필요없는 부분까지 전체를 받도록 해놨는데 이 부분 작업들 해야함.
월요일까지 일이 있어서 화요일 저녁부터 시작 가능할듯함.
이미지에 대한 부분도 빨리 생각해 볼게.

**Comment by zerstyu** [comment]
3. 농산물, 수산물, 축산물, 가공품, 기타 이중에 하나로 보내주세요.
4. RetailProduct는 메인 api에서 쓸 모델 들이라 프론트에선 안봐도 될 것 같은 느낌이네요.

**Comment by DevelopDestroyer** [comment]
@chudaeyoun 
@zerstyu 

**_1. 클라이언트에서 안넣어보내는게 맞는 것으로 결론_**

**_2. 아직 미구현_**

**3. 카테고리 문자열로 보내면 에러납니다.**
 "message": "JSON parse error: Cannot deserialize value of type `com.ugly.agri.type.CategoryType` from String \"농산물\": not one of the values accepted for Enum clas

**4. RetailProduct를 제외하고 전송시 에러가 발생합니다.**
{
  "statusCode": "FAIL",
  "message": "Validation failed for argument [0] in public com.ugly.agri.common.Response<com.ugly.agri.dto.ProductDTO> com.ugly.agri.controller.ProductController.createProduct(com.ugly.agri.dto.RequestProductDTO): [Field error in object 'requestProductDTO' on field 'retailProduct': rejected value [null]; codes [NotNull.requestProductDTO.retailProduct,NotNull.retailProduct,NotNull.com.ugly.agri.domain.RetailProduct,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [requestProductDTO.retailProduct,retailProduct]; arguments []; default message [retailProduct]]; default message [널이어서는 안됩니다]] ",
  "errorCode": "A001"
}

**_5. 아직 미구현_**

**_6. 미구현인데 생각 필요_** 

[추가 질문]
**7. 새로 생성될 상품의 ID를 모르는데 ID를 입력하라고 하고 있습니다. ID를 입력하지 않으면 에러가 발생합니다.**
{
  "statusCode": "FAIL",
  "message": "Validation failed for argument [0] in public com.ugly.agri.common.Response<com.ugly.agri.dto.ProductDTO> com.ugly.agri.controller.ProductController.createProduct(com.ugly.agri.dto.RequestProductDTO): [Field error in object 'requestProductDTO' on field 'id': rejected value [null]; codes [NotNull.requestProductDTO.id,NotNull.id,NotNull.java.lang.Long,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [requestProductDTO.id,id]; arguments []; default message [id]]; default message [널이어서는 안됩니다]] ",
  "errorCode": "A001"
}
그런데 대충 0 넣고 보내면 새로운 ID를 발급해주네요..
아래는 제가 보낸 리퀘스트 입니다. 이렇게 보내야 ok싸인이 떨어지네여

{
  "category": "AGRICULTURAL_PRODUCTS",
  "comment": "상품 좋아요~",
  "id": 0,
  "imageUrl": "img/test.jpg",
  "name": "밤고구마~",
  "price": 500,
  "userDTO": {
    "email": "test22",
    "id": 4,
    "name": "안녕"
  },
  "retailProduct": {
    "createdAt": "2020-11-23T16:05:25.552Z",
    "deletedAt": "2020-11-23T16:05:25.552Z",
    "grade": "string",
    "id": 1,
    "isDeleted": true,
    "kind": "string",
    "name": "string",
    "oneDayAvgPrice": "string",
    "oneMonthAvgPrice": "string",
    "oneWeekAvgPrice": "string",
    "oneYearAvgPrice": "string",
    "todayAvgPrice": "string",
    "twoWeekAvgPrice": "string",
    "updatedAt": "2020-11-23T16:05:25.552Z"
  }
}

----------------------------------------------------------

전체적으로 이 API가 클라이언트에서 바로 적용하기엔 오류도 있고 미완성된 부분이 많은 것 같습니다..
한번 검토 부탁드립니다.

**Comment by zerstyu** [comment]
Product > Category에서도 조회하는 곳처럼 enum string (농산물) 로 받아서 저장할 수 있게 하는 코드 추가해야할 듯

**Comment by zerstyu** [comment]
RetailProduct 은 null 이어도 되는 건가? 일단 메인화면에서 저희 데이터 잘 나오게 하려면, 필수값으로 하는 게 좋아보이네요.
RetailProduct api 만들어서 드릴게요. 그거 프론트에서 받아서 product 만들 때 select 하게끔 해야할 것 같아요.

**Comment by DevelopDestroyer** [comment]
@chudaeyoun 
@zerstyu 

[문의1]
swagger에 따르면
{
  "category": "string",
  "introduction": "string",
  "price": 0,
  "productionArea": "string",
  "productionDate": "string",
  "title": "string",
  "userId": 0
}
를 입력받고있는데요,

productionArea가 원산지, productionDate는 생산년월일인것으로 보입니다만
화면설계서(https://xd.adobe.com/view/43d212b7-bc29-4c46-abc1-53287c2f00f9-1681/screen/377c3402-7154-4d34-8524-6a3952b7f2ee/)에 따르면
상품정보에는 보관방법/취급방법, 개당 중량, 상품 구성 항목이 있습니다만 입력받는 필드가 누락되어 있는 것 같습니다.
확인 부탁드립니다.

[문의2]
조회API, GET /api/products는 매개변수로
{
  "categoryName": "농산물"
}
과 같은 형태로 받고 있습니다만, 시도를해보면 조회돼는 데이터가 없습니다.
테스트데이터가 없다면 기본데이터가 필요할것같으며, 아니라면 기능상에 문제가 있는 것인지 확인 부탁드립니다.
또한, 이 경우 전체카테고리를 대상으로 product 조회는 어떻게 해야하는지도 설명 부탁드립니다.

**Comment by zerstyu** [comment]
@DevelopDestroyer 
문의2는 제가 대답드릴게요.
컨트롤러 쪽에서 잘못받고 있었습니다.
해당 부분 수정해서 푸시해두었어요.
전체카테고리 대상 조회하는 방법은 categoryName을 없이 보내면 됩니다.
특정 카테고리 조회 방법은 "농산물", "수산물" 이런 식으로 보내주시면 되고요 ㅎㅎ

문의1은 @chudaeyoun 님이 확인 부탁드려요

**Comment by DevelopDestroyer** [comment]
@chudaeyoun 
@zerstyu 

[POST] api/products 사용시 여러 API에서 에러가 발생합니다.
예를들어 다음과 같은 데이터를 보내어 등록하면 성공적으로 등록이 됩니다만.
{
  "category": "수산물",
  "introduction": "테스트입니다",
  "price": 1000,
  "productionArea": "충남서산",
  "productionDate": "2019-12-12",
  "title": "string",
  "userId": 1
}

이후 
[GET] /api/products를 이용하여 "수산물"에 대한 데이터 조회를 시도하면
{
  "statusCode": "FAIL",
  "message": "java.lang.NullPointerException",
  "errorCode": "A002"
}
에러가 발생하며

[GET] /api/main/data 사용시
{
  "statusCode": "FAIL",
  "message": "java.lang.NullPointerException",
  "errorCode": "A002"
}
에러가 발생하며

[POST] /api/products를 다시 시도해보아도
{
  "statusCode": "FAIL",
  "message": "java.lang.NullPointerException",
  "errorCode": "A002"
}
에러가 발생합니다.

확인부탁드립니다.

**Comment by chudaeyoun** [comment]
-문의 1
이건 판매글에 올릴때 정보가 다 인줄 알았는데 화면에서 없었네.
상품상세 설명에 있는거대로 추가해둘게.

-[GET] /api/products
이건 내가 한거에 추가가 된거 같은데 보고 에러 수정하겠음.

**Comment by chudaeyoun** [comment]
-문의1 
누락분 추가 완료

-/api/products, /api/main/data  등 에러 나는 이유
상품등록할때 title 가지고 크롤링한 retailProduct name을 포함 하는 것을 보고 retailProduct를 세팅함.
그런데 test 할때 string 으로 해서 조회할때 retailProduct 이 null 이라 에러가 남.

@zerstyu
그래서 이 부분은 retailProduct name 이 없을때 default 값을 넣도록 만들어 줘야할듯

**Comment by DevelopDestroyer** [comment]
@chudaeyoun 

되돌려받는 데이터들에 부족한 내용들이 있습니다.
생산자, 개당 중량, 상품구성 등

**Comment by chudaeyoun** [comment]
@DevelopDestroyer 
누락데이터 추가함.

**Comment by DevelopDestroyer** [comment]
@chudaeyoun 
등록 API가 작동이 안됩니다. 확인 부탁드립니다.
* request
{
  "category": "농산물",
  "composition": "1",
  "introduction": "감자",
  "origin": "123",
  "price": 110,
  "producer": "1234",
  "productionArea": "12334",
  "productionDate": "2017-01-01",
  "storageMethod": "잘",
  "title": "감자",
  "userId": 1,
  "weightPerUnit": "12"
}

* response
{
  "statusCode": "FAIL",
  "message": "java.lang.NullPointerException",
  "errorCode": "A002"
}

**Comment by chudaeyoun** [comment]
@DevelopDestroyer 
상품 등록시에 product 엔티티에서 review 객체가 null 이여서 발생한 문제로
review 객체가 null 일때  생성해주는걸로 해결

**Comment by DevelopDestroyer** [comment]
이슈가 완료되어 닫습니다.
