### ISSUE TITLE
[main API] API 보완 검토 요청 드립니다.

### ISSUE THREAD

**Issue by DevelopDestroyer** [DevelopDestroyer/UglyAgriFood#14]
/api/main/data 에 대한 문의입니다.

1. 화면기획서에 따르면 특정 상품에 대해 시세가보다 얼마나 저렴한지 퍼센테이지로 표시해주는 부분이 있습니다. API에서는 해당 부분에 대한 정보를 별도로 제공하고 있지는 않은데 번거로우시다면 프론트에서 todayAvgPrice로 처리하는게 나으려나요?

2. price키의 값은 숫자형 (EX. 20000)인데 todayAvgPrice, oneDayAvgPrice ... 에서는 쉼표구분자(EX. 20,000)를 사용하고 있습니다. 통일하는 것이 좋을 것 같습니다. 위 1번을 프론트에서 처리해주시기 원하신다면 해당부분에 대한 처리는 백엔드에서 해주시는게 추후 개발에 있어서도 편리할 것 같습니다.

3. imageUrl의 경우 현재는 "img/~~~" 형태로 제공하고 있는데요, 경로가 아직 fix된건 아닌거지요? front가 사용하는 정적리소스 경로와 겹쳐지면 추후 문제가 생길 여지가 있을 수 있을것같아요

4.  category키의 값을 "농산", "수산"이 아닌 코드값(ex. AGRICULTURAL_PRODUCTS)의 형태로 반환하고 있는 것 같습니다.

5. relatedProductList(연관 상품)의 경우 화면설계서상에 어떤 영역에서 보여져야하는 건가요? 설계서 상에서는 특정고객에 대한 추천상품 리스트 => recommendProductList, 50%이상 할인된 품목들 =>  cheapProductList이 맞는 것 같은데 relatedProductList는 어디에 쓰이는 건지 궁금합니다

바쁘신데 긴글읽어주셔서 감사합니다 ! 

@zerstyu

**Comment by zerstyu** [comment]
1. 서버에서 처리하겠습니다. 크롤링 데이터 중에 프론트에서 뭐뭐가 필요한지를 몰라서 일단 저렇게 했는데.. pricePercent 필드 추가해두겠습니다!
2. 20000원, 20,000원 어떤 식으로 처리하는게 편할지 모르기 때문에 그냥 20000 이렇게 int 형으로 처리해두겠습니다.
3. @chudaeyoun 님이 답변 부탁드려요
4. 확인해보겠습니다.
5. 최근 본 상품에 대한 연관 상품들이라는 부분이 기획서 상에 있더라고요.

오늘 저녁에 작업해둘게요~

**Comment by zerstyu** [comment]
맞다 2번은 생각해보니, 가격은 BigDecimal 타입 써야 해요. (부동소수점)
product하고 retailProduct 쪽 가격 부분은 모두 bigdecimal로 변경해둘게요

**Comment by zerstyu** [comment]
흐음 원칙상 통화는 BigDecimal 타입을 쓰는 게 맞는데, 바꿔야 할 게 많네요. 그냥 대윤이처럼 Long 타입처리 해둘게요

**Comment by DevelopDestroyer** [comment]
@zerstyu 
화면기획서 상에 따르면.. 해당 API에 별점평균과 (0에서 5사이의 값), 총 리뷰수 카운터가 포함되어야 할 것 같습니다.
확인 부탁드립니다.

**Comment by DevelopDestroyer** [comment]
해결되어 이슈닫습니다.
