### ISSUE TITLE
[order API] 조회 시 에러 발생 문의

### ISSUE THREAD

**Issue by DevelopDestroyer** [DevelopDestroyer/UglyAgriFood#16]
@chudaeyoun 

userID : 2(유저계정은 chu로 확인됩니다)로 조회를 날리면 데이터가 날아오는데
에러코드가 함께날아와서 사용할수가 없는 상태입니다 (거의 도배급으로 에러가 떠서 글자수 제한으로 해당 깃허브 이슈폼에 내용을 올리기가 어렵습니다)
확인부탁드립니다.

p.s) 가급적 테스트를 위해 테스트를 위한데이터는 동일계정으로 통일되었으면 좋을것같아여

**Comment by zerstyu** [comment]
요건 확인해보니 product > review 쪽에서 뭔가 조건이 잘못걸렸는지 무한 recursive 돌아서 oom 에러 났네요

**Comment by zerstyu** [comment]
@chudaeyoun 
이런 식으로 해결함
https://pasudo123.tistory.com/350

**Comment by DevelopDestroyer** [comment]
완료되어 이슈를 닫습니다
