### ISSUE TITLE
[flile api] DB에 경로 저장 시 정형화가 필요할 것 같습니다.

### ISSUE THREAD

**Issue by DevelopDestroyer** [DevelopDestroyer/UglyAgriFood#23]
@chudaeyoun 
파일 등록 후 막상 GET을 해보면
      "mainImagePath": "/download\\3_mainImage.jpg",
      "thumbnailImagePath": "/download\\3_thumbnailImage.jpg",
와 같은 경로를 되돌려주는데... 웹브라우저에서 사용하기 적합하지 않은 것 같습니다.

뿐만아니라, 백슬래쉬 두개를 슬래쉬로 교체후 http://{서버호스트}:8080/download/3_mainImage.jpg을 하여도
정상적으로 표출이 안되고 있음을 알려드립니다..

수정 후 확인 부탁드립니다

**Comment by chudaeyoun** [comment]
@DevelopDestroyer 
정상적으로 mac 로컬과 서버에 
경로에 "/download\3_mainImage.jpg" 이게 아닌 "/download/3_mainImage.jpg" 이렇게 저장되는것 확인 됐는데 
어디서 안됨?

그리고 정상적으로 서버에서 호출시 정상동작 확인 됨.
http://35.185.255.70:8080/download/3_mainImage.jpg

**Comment by DevelopDestroyer** [comment]
확인 완료되었습니다 이슈 닫겠습니다
