### ISSUE TITLE
[user API] 동일한 ID 가입 중복처리가 되어있지 않습니다.

### ISSUE THREAD

**Issue by DevelopDestroyer** [DevelopDestroyer/UglyAgriFood#9]
이미 존재하는 email로 요청을 날려도 가입에 이상이 없습니다.
seq값은 primary하게 생성됩니다.

@chudaeyoun

**Comment by chudaeyoun** [comment]
@DevelopDestroyer 
이슈 수정 완료

https://github.com/DevelopDestroyer/UglyAgriFood/pull/10
